"""Writes planned + grounded agents as one YAML file per agent."""

from __future__ import annotations

from pathlib import Path

import yaml

from o2a_gen.config import GenConfig
from o2a_gen.plan import AgentNode, Plan

FIELD_ORDER = ("name", "agent_class", "version", "description", "input_keys", "output_key",
               "strict", "model", "tools", "instruction", "transform", "default_db_yaml",
               "routes", "sub_agents")


class _Dumper(yaml.SafeDumper):
    pass


def _str_rep(dumper, value: str):
    style = "|" if "\n" in value else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", value, style=style)


_Dumper.add_representer(str, _str_rep)


def dump_yaml(obj) -> str:
    return yaml.dump(obj, Dumper=_Dumper, sort_keys=False, allow_unicode=True, width=100)


def node_to_dict(node: AgentNode, cfg: GenConfig) -> dict:
    d: dict = {"name": node.name, "agent_class": node.agent_class}
    if node.description:
        d["description"] = node.description
    if node.output_key:
        d["output_key"] = node.output_key
    for k, v in node.fields.items():
        d[k] = v
    if node.children:
        d["sub_agents"] = [{"name": c.name} for c in node.children]
    for k, v in (cfg.agent_templates.get(node.agent_class) or {}).items():
        d.setdefault(k, v)
    ordered = {k: d[k] for k in FIELD_ORDER if k in d}
    ordered.update({k: v for k, v in d.items() if k not in ordered})
    return ordered


def write_plan(plan: Plan, cfg: GenConfig, out_dir: Path, source: str) -> list[Path]:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for node in plan.nodes():
        header = f"# Generated by o2a_gen from {source}"
        if node.step is not None:
            header += f", step {node.step.id} (lines {node.step.source_lines}): {node.step.title}"
        header += "\n# Review before use.\n"
        path = out_dir / f"{node.name}.yaml"
        path.write_text(header + dump_yaml(node_to_dict(node, cfg)), encoding="utf-8")
        written.append(path)
    return written
